const questionsEtica = [
    // --- Questões da Prova Enviada ---
    { q: "Ordenar dossiês pelo método dígito-terminal significa observar:", options: ["A ordem alfabética", "Os dígitos finais do número", "A data de nascimento", "O setor de trabalho"], correct: 1, subject: "Ética" },
    { q: "O arquivo com documentos de consultas frequentes é o:", options: ["Permanente", "Corrente", "Setorial", "Morto"], correct: 1, subject: "Ética" },
    { q: "Equipe que se reúne por tempo determinado para resolver problemas de prazos:", options: ["Multifuncional", "Autogerenciada", "De resolução de problemas", "De projetos"], correct: 2, subject: "Ética" },
    { q: "Atender 100 refugiados com 100 mil reais em um ano e 120 com 120 mil no outro indica que a ONG foi:", options: ["Mais eficiente", "Mais eficaz", "Mais produtiva", "Igualmente eficiente"], correct: 3, subject: "Ética" },
    { q: "Canal mais eficiente para comunicar regras de reembolso a 10 pessoas:", options: ["Telefone", "E-mail", "Palestra", "Reunião individual"], correct: 1, subject: "Ética" },
    { q: "O princípio da 'Amplitude de Controle' refere-se a:", options: ["Área total da empresa", "Número de subordinados por gestor", "Poder de punição", "Hierarquia salarial"], correct: 1, subject: "Ética" },
    { q: "No nível tático, as habilidades mais importantes são:", options: ["Técnicas", "Humanas", "Conceituais", "Manuais"], correct: 1, subject: "Ética" },
    { q: "Ao rever a estrutura de cargos, o diretor exerce a função de:", options: ["Planejamento", "Organização", "Direção", "Controle"], correct: 1, subject: "Ética" },
    { q: "Fator de contexto relacionado ao desempenho das equipes:", options: ["Diversidade", "Recursos adequados", "Propósito comum", "Metas específicas"], correct: 1, subject: "Ética" },
    { q: "Dar recompensas ao grupo em vez de individuais estimula a:", options: ["Competição", "Coesão", "Amplitude", "Departamentalização"], correct: 1, subject: "Ética" },
    // --- Questões Extras (Estilo FGV) ---
    { q: "A pirâmide que mostra necessidades fisiológicas na base e autorrealização no topo é de:", options: ["Herzberg", "Maslow", "McGregor", "Vroom"], correct: 1, subject: "Ética" },
    { q: "Poder formal exercido através de punições ou transferências forçadas:", options: ["Poder de Referência", "Poder Coercitivo", "Poder de Especialista", "Poder Legítimo"], correct: 1, subject: "Ética" },
    { q: "A barreira de comunicação 'Filtragem' ocorre quando:", options: ["A internet cai", "O emissor manipula a info para agradar o receptor", "O receptor está distraído", "O código é desconhecido"], correct: 1, subject: "Ética" },
    { q: "A departamentalização baseada em 'Auditoria, Consultoria e Contabilidade' é:", options: ["Por cliente", "Geográfica", "Funcional", "Por projetos"], correct: 2, subject: "Ética" },
    { q: "Uma desvantagem das equipes em relação ao trabalho individual:", options: ["Falta de criatividade", "Consumo de mais tempo e recursos", "Menor precisão", "Dificuldade de controle"], correct: 1, subject: "Ética" },
    { q: "Papel de quem examina detalhes e faz cumprir as regras na equipe:", options: ["Assessor", "Organizador", "Controlador", "Produtor"], correct: 2, subject: "Ética" },
    { q: "Comportamento que caracteriza a polidez no atendimento:", options: ["Usar verbos no imperativo", "Evitar o modo imperativo", "Falar o mínimo possível", "Ser informal demais"], correct: 1, subject: "Ética" },
    { q: "A função 'Controle' serve para:", options: ["Mandar nos funcionários", "Definir objetivos", "Monitorar e corrigir o desempenho", "Dividir o trabalho"], correct: 2, subject: "Ética" },
    { q: "O fluxograma é uma ferramenta utilizada para:", options: ["Ver as finanças", "Mapear processos", "Contratar pessoas", "Arquivar papéis"], correct: 1, subject: "Ética" },
    { q: "O documento que descreve a estrutura de uma organização é o:", options: ["Cronograma", "Organograma", "Histograma", "Dossiê"], correct: 1, subject: "Ética" },
    { q: "O Ciclo PDCA significa:", options: ["Planejar, Dirigir, Controlar, Agir", "Planejar, Fazer, Verificar, Agir", "Pagar, Delegar, Cobrar, Analisar", "Poder, Decisão, Comando, Autoridade"], correct: 1, subject: "Ética" },
    { q: "A meritocracia baseia-se em recompensar o funcionário por seu:", options: ["Tempo de casa", "Desempenho e mérito", "Grau de amizade", "Cargo ocupado"], correct: 1, subject: "Ética" },
    { q: "Na rede de comunicação tipo 'Roda', a figura central é o:", options: ["Cliente", "Líder", "Subordinado mais antigo", "Computador"], correct: 1, subject: "Ética" },
    { q: "A cultura organizacional é composta por:", options: ["Apenas as máquinas", "Valores, crenças e rituais da empresa", "O saldo bancário", "Os prédios da sede"], correct: 1, subject: "Ética" },
    { q: "Feedback é um processo de:", options: ["Punição", "Retorno de informação", "Silenciamento", "Demissão"], correct: 1, subject: "Ética" },
    { q: "A Teoria X e Y de McGregor trata sobre:", options: ["Finanças", "Percepção do gestor sobre a motivação humana", "Marketing", "Logística"], correct: 1, subject: "Ética" },
    { q: "A sigla IBGE significa:", options: ["Instituto Brasileiro de Geografia e Estatística", "Instituto de Bens de Geografia e Estado", "Igreja Brasileira de Geografia", "Instituto de Bases Geográficas"], correct: 0, subject: "Ética" },
    { q: "Documentos de valor histórico que nunca devem ser eliminados ficam no arquivo:", options: ["Corrente", "Intermediário", "Permanente", "Ativo"], correct: 2, subject: "Ética" },
    { q: "Benchmarking consiste em:", options: ["Demitir funcionários", "Comparar processos com as melhores práticas do mercado", "Esconder informações", "Reduzir salários"], correct: 1, subject: "Ética" },
    { q: "Liderança Democrática é aquela onde:", options: ["O líder decide tudo sozinho", "O grupo participa das decisões", "Não há líder", "O líder é autoritário"], correct: 1, subject: "Ética" },
    { q: "O método de arquivamento ordenado pelos dois últimos dígitos é o:", options: ["Alfabético", "Geográfico", "Dígito-terminal", "Numérico simples"], correct: 2, subject: "Ética" },
    { q: "Documentos objeto de consultas frequentes pertencem ao arquivo:", options: ["Permanente", "Corrente", "Intermediário", "De segurança"], correct: 1, subject: "Ética" },
    { q: "Equipe que se reúne para avaliar processos e propor melhorias de prazos:", options: ["Multifuncional", "Autogerenciada", "De resolução de problemas", "De projetos"], correct: 2, subject: "Ética" },
    { q: "O princípio que define o número de subordinados sob responsabilidade de um gestor:", options: ["Unidade de comando", "Amplitude de controle", "Nível de alçada", "Departamentalização"], correct: 1, subject: "Ética" },
    { q: "No nível TÁTICO da organização, as habilidades mais relevantes são as:", options: ["Técnicas", "Conceituais", "Humanas", "Decisórias"], correct: 2, subject: "Ética" },
    { q: "Atuar na revisão da estrutura de cargos do órgão é exercer a função de:", options: ["Planejamento", "Direção", "Organização", "Controle"], correct: 2, subject: "Ética" },
    { q: "A necessidade de 'pertencer a uma equipe e ser amigo de todos' refere-se à:", options: ["Realização", "Afiliação", "Poder", "Segurança"], correct: 1, subject: "Ética" },
    { q: "A Pirâmide de Maslow (da base para o topo) representa a teoria da:", options: ["Equidade", "Expectativa", "Hierarquia de necessidades", "Dois fatores"], correct: 2, subject: "Ética" },
    { q: "Poder exercido contra a vontade do subordinado (ex: transferência forçada):", options: ["Poder de Competência", "Poder Coercitivo", "Poder de Referência", "Poder Premiativo"], correct: 1, subject: "Ética" },
    { q: "A barreira de comunicação onde o emissor manipula a informação para o chefe:", options: ["Sobrecarga", "Percepção seletiva", "Filtragem", "Viés"], correct: 2, subject: "Ética" },
    { q: "Ética no IBGE exige decidir entre o:", options: ["Conveniente e oportuno", "Justo e injusto", "Honesto e desonesto", "Rápido e lento"], correct: 2, subject: "Ética" },
    { q: "É proibido ao servidor do IBGE:", options: ["Dar aulas", "Ser conivente com erro", "Defender cidadania", "Negar ordens ilegais"], correct: 1, subject: "Ética" },
    { q: "Pena de Censura exige parecer de:", options: ["Dois terços", "Diretor apenas", "Presidente apenas", "Unanimidade"], correct: 0, subject: "Ética" },
    { q: "Sigilo profissional no IBGE é:", options: ["Temporário", "Quebrável", "Perpétuo", "Opcional"], correct: 2, subject: "Ética" },
    { q: "Embriaguez habitual fora do serviço é:", options: ["Direito privado", "Falta ética", "Demissão imediata", "Doença apenas"], correct: 1, subject: "Ética" },
    { q: "Não prestar contas da conduta ética é:", options: ["Reserva", "Desrespeito ao cidadão", "Multa", "Inexistente"], correct: 1, subject: "Ética" },
    { q: "Cortesia no serviço público evita:", options: ["Amizades", "Filas", "Danos morais", "Rapidez"], correct: 2, subject: "Ética" },
    { q: "Comunicar atos contra interesse público exige:", options: ["Zelo e lealdade", "Dúvida", "Sigilo", "Indiferença"], correct: 0, subject: "Ética" },
    { q: "Usar cargo para favoritismo é:", options: ["Permitido família", "Vedação gravíssima", "Aceitável sem prejuízo", "Incentivado"], correct: 1, subject: "Ética" },
    { q: "Publicidade pode ser omitida em:", options: ["Custo alto", "Segurança nacional", "Pedido Governador", "Assunto menor"], correct: 1, subject: "Ética" },
    { q: "Fatos da vida privada do servidor:", options: ["Não influenciam", "Podem alterar bom conceito", "Só se for preso", "São sigilosos"], correct: 1, subject: "Ética" },
    { q: "Zelo e dedicação implicam em:", options: ["Evitar desperdício", "Só ordens diretas", "Horas extras", "Ignorar erros"], correct: 0, subject: "Ética" },
    { q: "Dados do informante são para:", options: ["Impostos", "Fins estatísticos", "Marketing", "Internet"], correct: 1, subject: "Ética" },
    { q: "Omitir denúncia antiética é:", options: ["Lealdade", "Conivência", "Prudência", "Silêncio"], correct: 1, subject: "Ética" },
    { q: "Registros de ética servem para:", options: ["Promoção", "Venda mailing", "Campanhas", "Privado"], correct: 0, subject: "Ética" },
    { q: "Deturpar documentos é:", options: ["Flexibilidade", "Crime e falta grave", "Permitido chefia", "Erro digital"], correct: 1, subject: "Ética" },
    { q: "Atrasos repetidos representam:", options: ["Falta motivação", "Desprezo dignidade", "Liberdade", "Direito"], correct: 1, subject: "Ética" },
    { q: "Servidor pode negar informação se:", options: ["Cansado", "Sigilo legal", "Não gostar", "Sistema lento"], correct: 1, subject: "Ética" },
    { q: "Trato com colegas baseia-se em:", options: ["Hierarquia riqueza", "Harmonia e cooperação", "Competição", "Formalidade"], correct: 1, subject: "Ética" },
    { q: "Desviar servidor para interesse particular é:", options: ["Urgência", "Vedação explícita", "Gestão moderna", "Necessidade"], correct: 1, subject: "Ética" },
    { q: "Verdade não pode ser omitida mesmo que:", options: ["Contrarie Administração", "Não perguntem", "Seja difícil", "Chefe mande"], correct: 0, subject: "Ética" },
    { q: "Comissão de Ética atua de forma:", options: ["Punitiva", "Pedagógica", "Oculta", "Lenta"], correct: 1, subject: "Ética" },
    { q: "Lucro pessoal com dados privilegiados é:", options: ["Bônus", "Infração grave", "Permitido", "Falta educação"], correct: 1, subject: "Ética" },
    { q: "Dano por negligência gera:", options: ["Perdão", "Exoneração", "Censura ética", "Nada"], correct: 2, subject: "Ética" },
    { q: "Facilitar fiscalização é:", options: ["Favor", "Dever fundamental", "Opcional", "Direito juiz"], correct: 1, subject: "Ética" },
    { q: "Falta ética no IBGE resulta em:", options: ["Prisão", "Multa", "Censura", "Perda política"], correct: 2, subject: "Ética" },
    { q: "Patrimônio público exige:", options: ["Desapego", "Evitar desperdício", "Uso pessoal", "Indiferença"], correct: 1, subject: "Ética" },
    { q: "Ética no serviço público visa:", options: ["Punição", "Imagem governo", "Bem comum", "Lucro"], correct: 2, subject: "Ética" },
    { q: "Honestidade deve ser praticada:", options: ["Com câmeras", "Ganhando bem", "Sempre", "Diante chefes"], correct: 2, subject: "Ética" },
    { q: "Decoro refere-se à conduta:", options: ["Só lei", "Honrosa à dignidade", "Barata", "Autopromoção"], correct: 1, subject: "Ética" }
];
