const questionsEtica = [
    { q: "A função pública deve ser vista como:", options: ["Ganho pessoal", "Exercício cidadania", "Fardo", "Privilégio"], correct: 1, subject: "Ética" },
    { q: "É dever do servidor do IBGE:", options: ["Omitir dados", "Ser cortês", "Atrasar", "Ignorar"], correct: 1, subject: "Ética" },
    { q: "Pode aceitar presentes de informantes?", options: ["Sim", "Não", "Só barato", "Feriados"], correct: 1, subject: "Ética" },
    { q: "Publicidade é regra, exceto em:", options: ["Segurança nacional", "Lazer", "Feriados", "Eventos"], correct: 0, subject: "Ética" },
    { q: "Elemento ético da conduta:", options: ["Diferenciar bem/mal", "Ganhar mais", "Trabalhar pouco", "Não ajudar"], correct: 0, subject: "Ética" },
    { q: "O que é vedado ao servidor?", options: ["Vida privada", "Cargo p/ benefício próprio", "Estudar", "Ser educado"], correct: 1, subject: "Ética" },
    { q: "Tratar mal um cidadão é:", options: ["Eficiência", "Dano moral", "Normal", "Necessário"], correct: 1, subject: "Ética" },
    { q: "A ética no IBGE visa:", options: ["Lucro", "Bem comum", "Fama", "Política"], correct: 1, subject: "Ética" },
    { q: "Mentir sobre dados no IBGE é:", options: ["Permitido", "Falta ética grave", "Opcional", "Útil"], correct: 1, subject: "Ética" },
    { q: "O trabalho do servidor é:", options: ["Inútil", "Patrimônio sociedade", "Só salário", "Privado"], correct: 1, subject: "Ética" },
    { q: "Moralidade administrativa foca em:", options: ["Legalidade/Justiça", "Só lucro", "Vontade chefe", "Rapidez"], correct: 0, subject: "Ética" },
    { q: "Respeitar hierarquia é dever?", options: ["Sim", "Não", "Às vezes", "Só Censo"], correct: 0, subject: "Ética" },
    { q: "Atrasos reiterados são:", options: ["Improbidade", "Falta compromisso", "Normais", "Aceitáveis"], correct: 1, subject: "Ética" },
    { q: "O sigilo estatístico protege:", options: ["Servidor", "Cidadão", "Governo", "Papel"], correct: 1, subject: "Ética" },
    { q: "Zelar pelos bens públicos é:", options: ["Facultativo", "Dever", "Só faxineiro", "Perda tempo"], correct: 1, subject: "Ética" },
    { q: "A cortesia é:", options: ["Dispensável", "Obrigatória", "Rara", "Opcional"], correct: 1, subject: "Ética" },
    { q: "Embriaguez habitual no serviço é:", options: ["Aceitável", "Vedação ética", "Só saúde", "Permitido"], correct: 1, subject: "Ética" },
    { q: "Vida privada influencia a honra?", options: ["Sim", "Jamais", "Não importa", "Só crime"], correct: 0, subject: "Ética" },
    { q: "Desviar servidor p/ fins particulares:", options: ["Liderança", "Imoral", "Prática comum", "Permitido"], correct: 1, subject: "Ética" },
    { q: "A quem pertence o código de ética?", options: ["Diretor", "Servidores", "Político", "Prédio"], correct: 1, subject: "Ética" },
    { q: "Primacial para o servidor:", options: ["Lucro", "Dignidade humana", "Política", "Agilidade"], correct: 1, subject: "Ética" },
    { q: "A quem prestar contas?", options: ["Só chefe", "Sociedade", "Partido", "Ninguém"], correct: 1, subject: "Ética" },
    { q: "Alterar dados intencionalmente:", options: ["Estratégia", "Crime/Falta grave", "Permitido", "Aceitável"], correct: 1, subject: "Ética" },
    { q: "Respeito à hierarquia deve ser:", options: ["Cego", "Dentro legalidade", "Só amizade", "Desconsiderado"], correct: 1, subject: "Ética" },
    { q: "Vida funcional deve espelhar:", options: ["Riqueza", "Vida privada", "Conduta ética", "Ambição"], correct: 2, subject: "Ética" },
    { q: "Documento que rege o servidor:", options: ["Só CF", "Código Ética IBGE", "Regimento", "C. Civil"], correct: 1, subject: "Ética" },
    { q: "Omitir verdade contra o Estado:", options: ["Lealdade", "Conduta antiética", "Dever", "Normal"], correct: 1, subject: "Ética" },
    { q: "Cortesia com usuário é:", options: ["Favor", "Dever fundamental", "Opcional", "Proibida"], correct: 1, subject: "Ética" },
    { q: "Zelar economia materiais é:", options: ["Mão vaquice", "Dever gestão", "Desnecessário", "Só compras"], correct: 1, subject: "Ética" },
    { q: "Uso uniforme/crachá serve p/:", options: ["Moda", "Segurança/Identificação", "Gastar", "Classes"], correct: 1, subject: "Ética" }
];