const questionsEtica = [
    { q: "O método de arquivamento ordenado pelos dois últimos dígitos é o:", options: ["Alfabético", "Geográfico", "Dígito-terminal", "Numérico simples"], correct: 2, subject: "Ética" },
    { q: "Documentos objeto de consultas frequentes pertencem ao arquivo:", options: ["Permanente", "Corrente", "Intermediário", "De segurança"], correct: 1, subject: "Ética" },
    { q: "Equipe que se reúne para avaliar processos e propor melhorias de prazos:", options: ["Multifuncional", "Autogerenciada", "De resolução de problemas", "De projetos"], correct: 2, subject: "Ética" },
    { q: "O princípio que define o número de subordinados sob responsabilidade de um gestor:", options: ["Unidade de comando", "Amplitude de controle", "Nível de alçada", "Departamentalização"], correct: 1, subject: "Ética" },
    { q: "No nível TÁTICO da organização, as habilidades mais relevantes são as:", options: ["Técnicas", "Conceituais", "Humanas", "Decisórias"], correct: 2, subject: "Ética" },
    { q: "Atuar na revisão da estrutura de cargos do órgão é exercer a função de:", options: ["Planejamento", "Direção", "Organização", "Controle"], correct: 2, subject: "Ética" },
    { q: "A necessidade de 'pertencer a uma equipe e ser amigo de todos' refere-se à:", options: ["Realização", "Afiliação", "Poder", "Segurança"], correct: 1, subject: "Ética" },
    { q: "A Pirâmide de Maslow (da base para o topo) representa a teoria da:", options: ["Equidade", "Expectativa", "Hierarquia de necessidades", "Dois fatores"], correct: 2, subject: "Ética" },
    { q: "Poder exercido contra a vontade do subordinado (ex: transferência forçada):", options: ["Poder de Competência", "Poder Coercitivo", "Poder de Referência", "Poder Premiativo"], correct: 1, subject: "Ética" },
    { q: "A barreira de comunicação onde o emissor manipula a informação para o chefe:", options: ["Sobrecarga", "Percepção seletiva", "Filtragem", "Viés"], correct: 2, subject: "Ética" },
    { q: "Ética no IBGE exige decidir entre o:", options: ["Conveniente e oportuno", "Justo e injusto", "Honesto e desonesto", "Rápido e lento"], correct: 2, subject: "Ética" },
    { q: "É proibido ao servidor do IBGE:", options: ["Dar aulas", "Ser conivente com erro", "Defender cidadania", "Negar ordens ilegais"], correct: 1, subject: "Ética" },
    { q: "Pena de Censura exige parecer de:", options: ["Dois terços", "Diretor apenas", "Presidente apenas", "Unanimidade"], correct: 0, subject: "Ética" },
    { q: "Sigilo profissional no IBGE é:", options: ["Temporário", "Quebrável", "Perpétuo", "Opcional"], correct: 2, subject: "Ética" },
    { q: "Embriaguez habitual fora do serviço é:", options: ["Direito privado", "Falta ética", "Demissão imediata", "Doença apenas"], correct: 1, subject: "Ética" },
    { q: "Não prestar contas da conduta ética é:", options: ["Reserva", "Desrespeito ao cidadão", "Multa", "Inexistente"], correct: 1, subject: "Ética" },
    { q: "Cortesia no serviço público evita:", options: ["Amizades", "Filas", "Danos morais", "Rapidez"], correct: 2, subject: "Ética" },
    { q: "Comunicar atos contra interesse público exige:", options: ["Zelo e lealdade", "Dúvida", "Sigilo", "Indiferença"], correct: 0, subject: "Ética" },
    { q: "Usar cargo para favoritismo é:", options: ["Permitido família", "Vedação gravíssima", "Aceitável sem prejuízo", "Incentivado"], correct: 1, subject: "Ética" },
    { q: "Publicidade pode ser omitida em:", options: ["Custo alto", "Segurança nacional", "Pedido Governador", "Assunto menor"], correct: 1, subject: "Ética" },
    { q: "Fatos da vida privada do servidor:", options: ["Não influenciam", "Podem alterar bom conceito", "Só se for preso", "São sigilosos"], correct: 1, subject: "Ética" },
    { q: "Zelo e dedicação implicam em:", options: ["Evitar desperdício", "Só ordens diretas", "Horas extras", "Ignorar erros"], correct: 0, subject: "Ética" },
    { q: "Dados do informante são para:", options: ["Impostos", "Fins estatísticos", "Marketing", "Internet"], correct: 1, subject: "Ética" },
    { q: "Omitir denúncia antiética é:", options: ["Lealdade", "Conivência", "Prudência", "Silêncio"], correct: 1, subject: "Ética" },
    { q: "Registros de ética servem para:", options: ["Promoção", "Venda mailing", "Campanhas", "Privado"], correct: 0, subject: "Ética" },
    { q: "Deturpar documentos é:", options: ["Flexibilidade", "Crime e falta grave", "Permitido chefia", "Erro digital"], correct: 1, subject: "Ética" },
    { q: "Atrasos repetidos representam:", options: ["Falta motivação", "Desprezo dignidade", "Liberdade", "Direito"], correct: 1, subject: "Ética" },
    { q: "Servidor pode negar informação se:", options: ["Cansado", "Sigilo legal", "Não gostar", "Sistema lento"], correct: 1, subject: "Ética" },
    { q: "Trato com colegas baseia-se em:", options: ["Hierarquia riqueza", "Harmonia e cooperação", "Competição", "Formalidade"], correct: 1, subject: "Ética" },
    { q: "Desviar servidor para interesse particular é:", options: ["Urgência", "Vedação explícita", "Gestão moderna", "Necessidade"], correct: 1, subject: "Ética" },
    { q: "Verdade não pode ser omitida mesmo que:", options: ["Contrarie Administração", "Não perguntem", "Seja difícil", "Chefe mande"], correct: 0, subject: "Ética" },
    { q: "Comissão de Ética atua de forma:", options: ["Punitiva", "Pedagógica", "Oculta", "Lenta"], correct: 1, subject: "Ética" },
    { q: "Lucro pessoal com dados privilegiados é:", options: ["Bônus", "Infração grave", "Permitido", "Falta educação"], correct: 1, subject: "Ética" },
    { q: "Dano por negligência gera:", options: ["Perdão", "Exoneração", "Censura ética", "Nada"], correct: 2, subject: "Ética" },
    { q: "Facilitar fiscalização é:", options: ["Favor", "Dever fundamental", "Opcional", "Direito juiz"], correct: 1, subject: "Ética" },
    { q: "Falta ética no IBGE resulta em:", options: ["Prisão", "Multa", "Censura", "Perda política"], correct: 2, subject: "Ética" },
    { q: "Patrimônio público exige:", options: ["Desapego", "Evitar desperdício", "Uso pessoal", "Indiferença"], correct: 1, subject: "Ética" },
    { q: "Ética no serviço público visa:", options: ["Punição", "Imagem governo", "Bem comum", "Lucro"], correct: 2, subject: "Ética" },
    { q: "Honestidade deve ser praticada:", options: ["Com câmeras", "Ganhando bem", "Sempre", "Diante chefes"], correct: 2, subject: "Ética" },
    { q: "Decoro refere-se à conduta:", options: ["Só lei", "Honrosa à dignidade", "Barata", "Autopromoção"], correct: 1, subject: "Ética" }
];
