const questionsGeo = [
    { q: "O Censo Demográfico ocorre normalmente a cada:", options: ["2 anos", "5 anos", "10 anos", "20 anos"], correct: 2, subject: "Geografia" },
    { q: "Qual a maior região em extensão territorial do Brasil?", options: ["Sul", "Nordeste", "Centro-Oeste", "Norte"], correct: 3, subject: "Geografia" },
    { q: "O bioma que ocupa a maior parte da região Nordeste é:", options: ["Pampas", "Caatinga", "Cerrado", "Pantanal"], correct: 1, subject: "Geografia" },
    { q: "O Brasil é dividido em quantas grandes regiões pelo IBGE?", options: ["4", "5", "6", "7"], correct: 1, subject: "Geografia" },
    { q: "Qual estado brasileiro possui a maior população?", options: ["Rio de Janeiro", "Bahia", "São Paulo", "Minas Gerais"], correct: 2, subject: "Geografia" },
    { q: "O ponto mais alto do relevo brasileiro é o:", options: ["Pico da Bandeira", "Pico do Jaraguá", "Pico da Neblina", "Pico das Agulhas Negras"], correct: 2, subject: "Geografia" },
    { q: "A zona de transição entre a Amazônia e a Caatinga é:", options: ["Mata de Cocais", "Manguezal", "Restinga", "Mata Atlântica"], correct: 0, subject: "Geografia" },
    { q: "Qual país não faz fronteira com o Brasil?", options: ["Chile", "Argentina", "Uruguai", "Bolívia"], correct: 0, subject: "Geografia" },
    { q: "O clima predominante na maior parte do território brasileiro é:", options: ["Temperado", "Equatorial", "Tropical", "Semiárido"], correct: 2, subject: "Geografia" },
    { q: "A pirâmide etária brasileira atual mostra um processo de:", options: ["Rejuvenescimento", "Envelhecimento da população", "Aumento da natalidade", "Diminuição da expectativa de vida"], correct: 1, subject: "Geografia" },
    { q: "O principal produto agrícola de exportação do Brasil é:", options: ["Arroz", "Trigo", "Soja", "Feijão"], correct: 2, subject: "Geografia" },
    { q: "A bacia hidrográfica totalmente brasileira é a de:", options: ["Amazonas", "Paraná", "Tocantins-Araguaia", "Paraguai"], correct: 2, subject: "Geografia" },
    { q: "O conceito de 'Região Metropolitana' envolve:", options: ["Um único município isolado", "Cidades que cresceram e se integraram (Conurbação)", "Apenas cidades do interior", "Zonas rurais"], correct: 1, subject: "Geografia" },
    { q: "A capital federal do Brasil localiza-se na região:", options: ["Sudeste", "Norte", "Centro-Oeste", "Sul"], correct: 2, subject: "Geografia" },
    { q: "O fuso horário oficial do Brasil (Brasília) está em relação a Greenwich:", options: ["-3 horas", "-4 horas", "+3 horas", "Igual"], correct: 0, subject: "Geografia" },
    { q: "A vegetação de mangue é típica de qual ambiente?", options: ["Desertos", "Altas montanhas", "Zonas costeiras/estuários", "Planalto central"], correct: 2, subject: "Geografia" },
    { q: "O Mercosul é um bloco econômico que inclui:", options: ["Brasil, Argentina, Uruguai e Paraguai", "Brasil, EUA e México", "Brasil e China", "Apenas países da Europa"], correct: 0, subject: "Geografia" },
    { q: "O êxodo rural é o movimento de pessoas da:", options: ["Cidade para o campo", "Cidade para outra cidade", "Campo para a cidade", "Brasil para o exterior"], correct: 2, subject: "Geografia" },
    { q: "O IDH (Índice de Desenvolvimento Humano) mede:", options: ["Apenas a riqueza", "Saúde, Educação e Renda", "Apenas a quantidade de filhos", "A força militar"], correct: 1, subject: "Geografia" },
    { q: "O relevo brasileiro é caracterizado por:", options: ["Grandes cadeias de montanhas recentes", "Planaltos, planícies e depressões antigas", "Vulcões ativos", "Geleiras eternas"], correct: 1, subject: "Geografia" },
    { q: "A principal fonte de energia elétrica do Brasil é:", options: ["Nuclear", "Solar", "Hidrelétrica", "Eólica"], correct: 2, subject: "Geografia" },
    { q: "Qual destas é uma cidade planejada?", options: ["Rio de Janeiro", "Salvador", "Brasília", "Recife"], correct: 2, subject: "Geografia" },
    { q: "O aquífero Guarani é um importante reservatório de:", options: ["Petróleo", "Gás natural", "Água doce subterrânea", "Ouro"], correct: 2, subject: "Geografia" },
    { q: "A linha imaginária que divide a Terra em Norte e Sul é:", options: ["Meridiano de Greenwich", "Círculo Polar", "Equador", "Trópico de Câncer"], correct: 2, subject: "Geografia" },
    { q: "A maior cidade do Brasil em população é:", options: ["Brasília", "São Paulo", "Rio de Janeiro", "Belo Horizonte"], correct: 1, subject: "Geografia" },
    { q: "O setor da economia que engloba o comércio e serviços é o:", options: ["Primário", "Secundário", "Terciário", "Quaternário"], correct: 2, subject: "Geografia" },
    { q: "A densidade demográfica mede:", options: ["Total de mortes", "Habitantes por km²", "Apenas a área urbana", "O total de prédios"], correct: 1, subject: "Geografia" },
    { q: "O fenômeno do El Niño afeta:", options: ["O clima global através do aquecimento das águas do Pacífico", "Apenas a Lua", "O preço do dólar", "As marés do Atlântico apenas"], correct: 0, subject: "Geografia" },
    { q: "O Pantanal localiza-se nos estados de:", options: ["MG e SP", "MS e MT", "RS e SC", "AM e PA"], correct: 1, subject: "Geografia" },
    { q: "Qual desses estados pertence à região Norte?", options: ["Maranhão", "Tocantins", "Piauí", "Goiás"], correct: 1, subject: "Geografia" },
    { q: "Ritmo menor de crescimento no Censo 2022 deve-se à:", options: ["Mortalidade infantil", "Queda da fecundidade", "Expectativa vida", "Êxodo rural"], correct: 1, subject: "Geografia" },
    { q: "Conceito de 'Região Concentrada' foca no:", options: ["Nordeste", "Centro-Oeste", "Sul e Sudeste", "Norte"], correct: 2, subject: "Geografia" },
    { q: "Região MATOPIBA foca no bioma:", options: ["Pampa", "Cerrado", "Pantanal", "Amazônia"], correct: 1, subject: "Geografia" },
    { q: "Relevo brasileiro caracteriza-se por:", options: ["Dobramentos modernos", "Planaltos e depressões", "Vulcões ativos", "Montanhas jovens"], correct: 1, subject: "Geografia" },
    { q: "Massa de ar das chuvas de verão no Sudeste:", options: ["mPa", "mEc", "mTa", "mTc"], correct: 1, subject: "Geografia" },
    { q: "Gentrificação urbana resulta em:", options: ["Melhoria para pobres", "Expulsão baixa renda", "Produção urbana", "Descentralização"], correct: 1, subject: "Geografia" },
    { q: "Maior bacia totalmente brasileira:", options: ["Amazonas", "Paraná", "São Francisco", "Tocantins-Araguaia"], correct: 3, subject: "Geografia" },
    { q: "El Niño no Nordeste provoca:", options: ["Enchentes", "Geadas", "Secas", "Frio"], correct: 2, subject: "Geografia" },
    { q: "Transição Cerrado e Amazônia:", options: ["Caatinga", "Mata Cocais", "Manguezal", "Igapó"], correct: 1, subject: "Geografia" },
    { q: "REGIC identifica a:", options: ["Divisão política", "Hierarquia urbana", "Fauna", "Preservação"], correct: 1, subject: "Geografia" },
    { q: "Corpo largo na pirâmide demográfica indica:", options: ["Bônus Demográfico", "Envelhecimento", "Natalidade", "Déficit"], correct: 0, subject: "Geografia" },
    { q: "Setor com melhor saldo comercial recente:", options: ["Indústria", "Serviços", "Agropecuário", "Tecnologia"], correct: 2, subject: "Geografia" },
    { q: "Macrocefalia Urbana é:", options: ["Igualdade recursos", "Concentração excessiva", "Fim periferias", "Menos violência"], correct: 1, subject: "Geografia" },
    { q: "Mares de Morros localizam-se no:", options: ["Sudeste", "Central", "Pampas", "Borda Amazônica"], correct: 0, subject: "Geografia" },
    { q: "Energia Eólica cresceu mais no:", options: ["Sul", "Sudeste", "Nordeste", "Centro-Oeste"], correct: 2, subject: "Geografia" },
    { q: "Causa da Friagem no Norte:", options: ["mTc", "mPa", "mEc", "mTa"], correct: 1, subject: "Geografia" },
    { q: "Territórios Quilombolas ganharam destaque no:", options: ["Censo 2000", "Censo 2010", "Censo 2022", "Censo Agro"], correct: 2, subject: "Geografia" },
    { q: "Terra Roxa é típica do:", options: ["Nordeste", "Sul e Sudeste", "Norte", "Litoral"], correct: 1, subject: "Geografia" },
    { q: "Mercosul é uma:", options: ["Livre Comércio", "União Aduaneira", "União Monetária", "Zona Franca"], correct: 1, subject: "Geografia" },
    { q: "Maior densidade demográfica brasileira:", options: ["Ocidental", "Central", "Litorânea", "Norte"], correct: 2, subject: "Geografia" },
    { q: "Bioma 'Caixa d'água do Brasil':", options: ["Amazônia", "Cerrado", "Caatinga", "Pantanal"], correct: 1, subject: "Geografia" },
    { q: "Fuso de Noronha em relação a Brasília:", options: ["-1 hora", "+1 hora", "-2 horas", "+2 horas"], correct: 1, subject: "Geografia" },
    { q: "Lixiviação resulta em:", options: ["Fertilidade", "Lavagem nutrientes", "Compactação", "Irrigação"], correct: 1, subject: "Geografia" },
    { q: "Transamazônica foi obra do:", options: ["Vargas", "Regime Militar", "JK", "Anos 90"], correct: 1, subject: "Geografia" },
    { q: "Porto líder na América Latina:", options: ["Paranaguá", "Santos", "Suape", "Itaqui"], correct: 1, subject: "Geografia" },
    { q: "Conurbação ocorre quando:", options: ["Cidades se unem", "Êxodo rural", "Cidade abandonada", "Favelas"], correct: 0, subject: "Geografia" },
    { q: "Vegetação xerófila é da:", options: ["Cerrado", "Caatinga", "Pampas", "Mata Atlântica"], correct: 1, subject: "Geografia" },
    { q: "Quadrilátero Ferrífero está em:", options: ["Pará", "Minas Gerais", "Mato Grosso", "ES"], correct: 1, subject: "Geografia" },
    { q: "Projeção de Peters é:", options: ["Conforme", "Equivalente", "Afilática", "Cilíndrica"], correct: 1, subject: "Geografia" },
    { q: "Estados do Centro-Oeste (sem DF):", options: ["2", "3", "4", "5"], correct: 1, subject: "Geografia" }
];
