const questionsGeo = [
    { q: "Ritmo menor de crescimento no Censo 2022 deve-se à:", options: ["Mortalidade infantil", "Queda da fecundidade", "Expectativa vida", "Êxodo rural"], correct: 1, subject: "Geografia" },
    { q: "Conceito de 'Região Concentrada' foca no:", options: ["Nordeste", "Centro-Oeste", "Sul e Sudeste", "Norte"], correct: 2, subject: "Geografia" },
    { q: "Região MATOPIBA foca no bioma:", options: ["Pampa", "Cerrado", "Pantanal", "Amazônia"], correct: 1, subject: "Geografia" },
    { q: "Relevo brasileiro caracteriza-se por:", options: ["Dobramentos modernos", "Planaltos e depressões", "Vulcões ativos", "Montanhas jovens"], correct: 1, subject: "Geografia" },
    { q: "Massa de ar das chuvas de verão no Sudeste:", options: ["mPa", "mEc", "mTa", "mTc"], correct: 1, subject: "Geografia" },
    { q: "Gentrificação urbana resulta em:", options: ["Melhoria para pobres", "Expulsão baixa renda", "Produção urbana", "Descentralização"], correct: 1, subject: "Geografia" },
    { q: "Maior bacia totalmente brasileira:", options: ["Amazonas", "Paraná", "São Francisco", "Tocantins-Araguaia"], correct: 3, subject: "Geografia" },
    { q: "El Niño no Nordeste provoca:", options: ["Enchentes", "Geadas", "Secas", "Frio"], correct: 2, subject: "Geografia" },
    { q: "Transição Cerrado e Amazônia:", options: ["Caatinga", "Mata Cocais", "Manguezal", "Igapó"], correct: 1, subject: "Geografia" },
    { q: "REGIC identifica a:", options: ["Divisão política", "Hierarquia urbana", "Fauna", "Preservação"], correct: 1, subject: "Geografia" },
    { q: "Corpo largo na pirâmide demográfica indica:", options: ["Bônus Demográfico", "Envelhecimento", "Natalidade", "Déficit"], correct: 0, subject: "Geografia" },
    { q: "Setor com melhor saldo comercial recente:", options: ["Indústria", "Serviços", "Agropecuário", "Tecnologia"], correct: 2, subject: "Geografia" },
    { q: "Macrocefalia Urbana é:", options: ["Igualdade recursos", "Concentração excessiva", "Fim periferias", "Menos violência"], correct: 1, subject: "Geografia" },
    { q: "Mares de Morros localizam-se no:", options: ["Sudeste", "Central", "Pampas", "Borda Amazônica"], correct: 0, subject: "Geografia" },
    { q: "Energia Eólica cresceu mais no:", options: ["Sul", "Sudeste", "Nordeste", "Centro-Oeste"], correct: 2, subject: "Geografia" },
    { q: "Causa da Friagem no Norte:", options: ["mTc", "mPa", "mEc", "mTa"], correct: 1, subject: "Geografia" },
    { q: "Territórios Quilombolas ganharam destaque no:", options: ["Censo 2000", "Censo 2010", "Censo 2022", "Censo Agro"], correct: 2, subject: "Geografia" },
    { q: "Terra Roxa é típica do:", options: ["Nordeste", "Sul e Sudeste", "Norte", "Litoral"], correct: 1, subject: "Geografia" },
    { q: "Mercosul é uma:", options: ["Livre Comércio", "União Aduaneira", "União Monetária", "Zona Franca"], correct: 1, subject: "Geografia" },
    { q: "Maior densidade demográfica brasileira:", options: ["Ocidental", "Central", "Litorânea", "Norte"], correct: 2, subject: "Geografia" },
    { q: "Bioma 'Caixa d'água do Brasil':", options: ["Amazônia", "Cerrado", "Caatinga", "Pantanal"], correct: 1, subject: "Geografia" },
    { q: "Fuso de Noronha em relação a Brasília:", options: ["-1 hora", "+1 hora", "-2 horas", "+2 horas"], correct: 1, subject: "Geografia" },
    { q: "Lixiviação resulta em:", options: ["Fertilidade", "Lavagem nutrientes", "Compactação", "Irrigação"], correct: 1, subject: "Geografia" },
    { q: "Transamazônica foi obra do:", options: ["Vargas", "Regime Militar", "JK", "Anos 90"], correct: 1, subject: "Geografia" },
    { q: "Porto líder na América Latina:", options: ["Paranaguá", "Santos", "Suape", "Itaqui"], correct: 1, subject: "Geografia" },
    { q: "Conurbação ocorre quando:", options: ["Cidades se unem", "Êxodo rural", "Cidade abandonada", "Favelas"], correct: 0, subject: "Geografia" },
    { q: "Vegetação xerófila é da:", options: ["Cerrado", "Caatinga", "Pampas", "Mata Atlântica"], correct: 1, subject: "Geografia" },
    { q: "Quadrilátero Ferrífero está em:", options: ["Pará", "Minas Gerais", "Mato Grosso", "ES"], correct: 1, subject: "Geografia" },
    { q: "Projeção de Peters é:", options: ["Conforme", "Equivalente", "Afilática", "Cilíndrica"], correct: 1, subject: "Geografia" },
    { q: "Estados do Centro-Oeste (sem DF):", options: ["2", "3", "4", "5"], correct: 1, subject: "Geografia" }
];
