const questionsGeo = [
    { q: "Qual a capital do Tocantins?", options: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional"], correct: 0, subject: "Geografia" },
    { q: "Brasil faz fronteira com quantos países na Am. do Sul?", options: ["8", "9", "10", "12"], correct: 2, subject: "Geografia" },
    { q: "Principal rio da Bacia Amazônica:", options: ["Paraná", "São Francisco", "Amazonas", "Tietê"], correct: 2, subject: "Geografia" },
    { q: "O clima predominante no Nordeste é:", options: ["Equatorial", "Semiárido", "Subtropical", "Temperado"], correct: 1, subject: "Geografia" },
    { q: "O que é o êxodo rural?", options: ["Cidade p/ campo", "Campo p/ cidade", "Mudança entre países", "Turismo"], correct: 1, subject: "Geografia" },
    { q: "Qual a maior região em número de estados?", options: ["Norte", "Nordeste", "Sudeste", "Sul"], correct: 1, subject: "Geografia" },
    { q: "Atividade econômica do Centro-Oeste:", options: ["Indústria", "Pesca", "Agropecuária", "Turismo"], correct: 2, subject: "Geografia" },
    { q: "O que o IBGE mede com o IPCA?", options: ["População", "Inflação", "Área", "Altitude"], correct: 1, subject: "Geografia" },
    { q: "País que NÃO faz fronteira com o Brasil:", options: ["Chile", "Argentina", "Uruguai", "Peru"], correct: 0, subject: "Geografia" },
    { q: "Bioma exclusivo do Brasil:", options: ["Cerrado", "Caatinga", "Amazônia", "Pantanal"], correct: 1, subject: "Geografia" },
    { q: "Ponto mais alto do Brasil:", options: ["Pico Bandeira", "Pico Neblina", "Pico Jaraguá", "Corcovado"], correct: 1, subject: "Geografia" },
    { q: "Estado com menor extensão territorial:", options: ["Sergipe", "Alagoas", "Espírito Santo", "Acre"], correct: 0, subject: "Geografia" },
    { q: "O que é densidade demográfica?", options: ["Total mortes", "Hab/km²", "Total nascimentos", "Área"], correct: 1, subject: "Geografia" },
    { q: "Estação que começa em 21 de Dezembro:", options: ["Inverno", "Outono", "Verão", "Primavera"], correct: 2, subject: "Geografia" },
    { q: "Vegetação do Sul do Brasil:", options: ["Cerrado", "Pampas", "Caatinga", "Mangue"], correct: 1, subject: "Geografia" },
    { q: "Maior produtor de café do Brasil:", options: ["Minas Gerais", "Rio de Janeiro", "Goiás", "Amazonas"], correct: 0, subject: "Geografia" },
    { q: "Fuso horário de Brasília:", options: ["GMT -1", "GMT -2", "GMT -3", "GMT -4"], correct: 2, subject: "Geografia" },
    { q: "O Brasil está em qual continente?", options: ["Africano", "Europeu", "Americano", "Asiático"], correct: 2, subject: "Geografia" },
    { q: "Oceano que banha o Brasil:", options: ["Pacífico", "Índico", "Atlântico", "Ártico"], correct: 2, subject: "Geografia" },
    { q: "A Transamazônica é uma:", options: ["Ferrovia", "Hidrovia", "Rodovia", "Ciclovia"], correct: 2, subject: "Geografia" },
    { q: "Estado brasileiro com maior PIB:", options: ["RJ", "MG", "SP", "PR"], correct: 2, subject: "Geografia" },
    { q: "Sede da Zona Franca:", options: ["Manaus", "Belém", "Recife", "Salvador"], correct: 0, subject: "Geografia" },
    { q: "O El Niño ocorre em qual oceano?", options: ["Atlântico", "Índico", "Pacífico", "Ártico"], correct: 2, subject: "Geografia" },
    { q: "Principal fonte de energia elétrica BR:", options: ["Solar", "Eólica", "Hidrelétrica", "Termo"], correct: 2, subject: "Geografia" },
    { q: "O Quadrilátero Ferrífero fica em:", options: ["GO", "PA", "MT", "MG"], correct: 3, subject: "Geografia" },
    { q: "Vegetação do Pantanal é:", options: ["Mata fechada", "Mosaico", "Só cactos", "Pinheiros"], correct: 1, subject: "Geografia" },
    { q: "Brasil está no hemisfério predominante:", options: ["Norte", "Sul", "Leste", "Ocidental"], correct: 1, subject: "Geografia" },
    { q: "Cidade sede do IBGE:", options: ["Brasília", "São Paulo", "Rio de Janeiro", "BH"], correct: 2, subject: "Geografia" },
    { q: "O que é o Censo Demográfico?", options: ["Prod. Agrícola", "Contagem População", "Medição terras", "Preços"], correct: 1, subject: "Geografia" },
    { q: "País vizinho que não fala espanhol:", options: ["Suriname", "Argentina", "Paraguai", "Bolívia"], correct: 0, subject: "Geografia" }
];