const questionsMat = [
    // --- Questões da Prova Enviada ---
    { q: "Felipe gastou R$90 em meias de R$12 e R$15. Sabendo que comprou ao menos uma de R$15, qual o máximo de pares de R$12?", options: ["6", "5", "4", "3"], correct: 1, subject: "Matemática" },
    { q: "Sérgio deve R$7,50. Qual a diferença entre a maior e menor quantidade de moedas (0,25, 0,50 ou 1,00) para pagar?", options: ["22", "20", "17", "15"], correct: 1, subject: "Matemática" },
    { q: "Juliana lê livros em 2, 3, 4 dias... Terminou o 1º num domingo e o 2º quarta. O 10º termina em um(a):", options: ["Sábado", "Domingo", "Segunda", "Quarta"], correct: 1, subject: "Matemática" },
    { q: "Leo atendeu 24 pacientes/dia por 3 dias e 32 pacientes/dia por 2 dias. Total de pacientes:", options: ["56", "136", "124", "140"], correct: 1, subject: "Matemática" },
    { q: "Se Roberto é vascaíno, Jair é botafoguense. Se Roberto não é, Sérgio é tricolor. Conclui-se que:", options: ["Se Jair não é botafoguense, Sérgio é tricolor", "Se Sérgio é tricolor, Roberto é vascaíno", "Jair é tricolor", "Roberto é botafoguense"], correct: 0, subject: "Matemática" },
    { q: "Equipe de 60 membros tem 6 mulheres a mais que homens. Razão mulheres/homens:", options: ["11/9", "5/6", "4/5", "11/20"], correct: 0, subject: "Matemática" },
    { q: "Arquimedes corria 15km em 1h45min. Agora caminha 8km em 1h20min. Para 1km ele precisa de mais:", options: ["2 min", "3 min", "5 min", "10 min"], correct: 1, subject: "Matemática" },
    { q: "Sete amigos dividem a conta. Um esqueceu o dinheiro e os outros pagaram +R$14,50 cada. Valor total:", options: ["R$522", "R$567", "R$588", "R$609"], correct: 3, subject: "Matemática" },
    { q: "Lucas gasta 1h20min no trânsito. Sem trânsito (+20km/h) gasta 48min. Distância casa-trabalho:", options: ["36km", "40km", "48km", "60km"], correct: 1, subject: "Matemática" },
    { q: "Cada chiclete R$1. Pacote com 5 é R$4. Pacote com 10 é R$7. Com R$90, o máximo de chicletes é:", options: ["103", "115", "127", "128"], correct: 2, subject: "Matemática" },
    // --- Questões Extras (Estilo FGV) ---
    { q: "Em uma gaveta há 5 pares de meias pretas e 5 brancas. Quantas meias retirar para ter certeza de um par da mesma cor?", options: ["2", "3", "5", "11"], correct: 1, subject: "Matemática" },
    { q: "A negação de 'Todo recenseador é treinado' é:", options: ["Nenhum recenseador é treinado", "Algum recenseador não é treinado", "Todos são treinados", "Algum recenseador é treinado"], correct: 1, subject: "Matemática" },
    { q: "Um produto custa R$200. Sofre aumento de 10% e depois desconto de 10%. Valor final:", options: ["R$200", "R$198", "R$210", "R$180"], correct: 1, subject: "Matemática" },
    { q: "Quantos números de 1 a 100 são múltiplos de 3 e 5 ao mesmo tempo?", options: ["6", "10", "15", "20"], correct: 0, subject: "Matemática" },
    { q: "Se ontem foi terça-feira, que dia será daqui a 50 dias?", options: ["Quarta", "Quinta", "Sexta", "Sábado"], correct: 1, subject: "Matemática" },
    { q: "Média aritmética de 10, 20, 30 e 60 é:", options: ["30", "40", "25", "20"], correct: 0, subject: "Matemática" },
    { q: "Um mapa tem escala 1:100.000. Se no mapa a distância é 5cm, a real é:", options: ["5km", "50km", "500m", "50km"], correct: 0, subject: "Matemática" },
    { q: "Quantos minutos há em 2,5 horas?", options: ["120", "150", "250", "130"], correct: 1, subject: "Matemática" },
    { q: "Se 'Se chove, a rua molha' é verdade, então:", options: ["Se a rua está molhada, choveu", "Se a rua não molhou, não choveu", "Sempre chove", "A rua nunca molha"], correct: 1, subject: "Matemática" },
    { q: "Área de um retângulo de 10m por 5m:", options: ["15m²", "50m²", "30m²", "25m²"], correct: 1, subject: "Matemática" },
    { q: "Um bolo leva 3 ovos. Para 12 bolos, quantos ovos?", options: ["15", "24", "36", "48"], correct: 2, subject: "Matemática" },
    { q: "A terça parte de 90 somada com o dobro de 10 é:", options: ["40", "50", "60", "30"], correct: 1, subject: "Matemática" },
    { q: "Se A={1,2,3} e B={3,4,5}, a intersecção A∩B é:", options: ["{1,2,3,4,5}", "{3}", "{1,2}", "{4,5}"], correct: 1, subject: "Matemática" },
    { q: "Raiz quadrada de 144:", options: ["10", "11", "12", "14"], correct: 2, subject: "Matemática" },
    { q: "Uma caixa d'água de 1m³ comporta quantos litros?", options: ["100", "500", "1000", "2000"], correct: 2, subject: "Matemática" },
    { q: "Se 4 máquinas produzem 40 peças, 8 máquinas produzem:", options: ["60", "80", "100", "120"], correct: 1, subject: "Matemática" },
    { q: "Um ângulo reto possui:", options: ["45°", "90°", "180°", "360°"], correct: 1, subject: "Matemática" },
    { q: "Qual o próximo número da sequência: 2, 4, 8, 16, ...?", options: ["20", "24", "30", "32"], correct: 3, subject: "Matemática" },
    { q: "Se x + 10 = 25, o valor de x é:", options: ["10", "15", "20", "35"], correct: 1, subject: "Matemática" },
    { q: "Um desconto de 25% sobre R$80,00 resulta em:", options: ["R$20", "R$60", "R$40", "R$75"], correct: 1, subject: "Matemática" },
    { q: "Felipe gastou R$90 com meias de R$12 e R$15. Qual o máximo de pares de R$12 que ele comprou?", options: ["6", "5", "4", "3"], correct: 1, subject: "Matemática" },
    { q: "Sérgio deve R$7,50. Usando moedas de 0,25, 0,50 ou 1,00, qual a diferença entre a maior e menor quantidade de moedas?", options: ["20", "22", "15", "12"], correct: 1, subject: "Matemática" },
    { q: "Uma equipe tem 60 membros, sendo 6 mulheres a mais que homens. A razão mulheres/homens é:", options: ["11/9", "9/11", "33/27", "5/6"], correct: 0, subject: "Matemática" },
    { q: "Sete amigos dividem a conta. Um esqueceu a carteira e cada um pagou +R$14,50. O total foi:", options: ["R$522", "R$609", "R$588", "R$630"], correct: 1, subject: "Matemática" },
    { q: "Se Roberto é vascaíno, Jair é botafoguense. Se Jair não é botafoguense, conclui-se:", options: ["Sérgio é tricolor", "Roberto não é vascaíno", "Roberto é vascaíno", "Jair é vascaíno"], correct: 1, subject: "Matemática" },
    { q: "Cada chiclete custa R$1. Pacote com 5 custa R$4 e com 10 custa R$7. Com R$90, Bia compra no máximo:", options: ["103", "115", "127", "128"], correct: 2, subject: "Matemática" },
    { q: "Lucas gasta 1h20min no trânsito. Sem trânsito (20km/h a mais) gasta 48min. A distância é:", options: ["36km", "40km", "48km", "60km"], correct: 1, subject: "Matemática" },
    { q: "Juliana lê livros em 2, 3, 4 dias... sucessivamente. Terminou o 1º domingo e o 2º quarta. O 10º termina:", options: ["Sábado", "Domingo", "Segunda", "Quarta"], correct: 1, subject: "Matemática" },
    { q: "Leo atendeu 24 pacientes/dia por 3 dias e 32 pacientes/dia por 2 dias. O total foi:", options: ["56", "136", "124", "140"], correct: 1, subject: "Matemática" },
    { q: "Arquimedes corria 15km em 1h45min. Agora caminha 8km em 1h20min. Para 1km ele gasta a mais:", options: ["2 min", "3 min", "5 min", "10 min"], correct: 1, subject: "Matemática" },
    { q: "Se 3 recenseadores visitam 120 casas em 4 dias, quantos dias 2 levarão para 100 casas?", options: ["5 dias", "6 dias", "4 dias", "8 dias"], correct: 1, subject: "Matemática" },
    { q: "A negação de 'Todo recenseador usa colete' é:", options: ["Nenhum usa colete.", "Algum não usa colete.", "Todos usam colete.", "Algum usa colete."], correct: 1, subject: "Matemática" },
    { q: "Um aluguel de 25% da renda subiu 10%. Quanto da renda ocupará agora?", options: ["35%", "27,5%", "26%", "30%"], correct: 1, subject: "Matemática" },
    { q: "Se 'P então Q' é falso, então:", options: ["P e Q falsos.", "P verdade e Q falso.", "P falso e Q verdade.", "P e Q verdades."], correct: 1, subject: "Matemática" },
    { q: "Produto de R$ 80 teve aumento de 20% e desconto de 20%. Preço final:", options: ["R$ 80,00", "R$ 76,80", "R$ 64,00", "R$ 82,40"], correct: 1, subject: "Matemática" },
    { q: "60 homens e 40 mulheres. 20% dos homens e 10% das mulheres não responderam. Total:", options: ["12", "16", "20", "25"], correct: 1, subject: "Matemática" },
    { q: "Próximo número da sequência: 2, 3, 5, 8, 12...?", options: ["15", "17", "18", "20"], correct: 1, subject: "Matemática" },
    { q: "Média de 3 pessoas é 20 anos. Entra uma de 40 anos. Nova média:", options: ["22 anos", "25 anos", "28 anos", "30 anos"], correct: 1, subject: "Matemática" },
    { q: "5 bolas azuis e 3 vermelhas. Sorteando duas sem reposição, ambas azuis:", options: ["25/64", "5/14", "10/28", "20/56"], correct: 1, subject: "Matemática" },
    { q: "4 canetas e 3 lápis = R$ 15. 2 canetas e 1 lápis = R$ 7. Caneta custa:", options: ["R$ 2,00", "R$ 3,00", "R$ 4,00", "R$ 2,50"], correct: 1, subject: "Matemática" },
    { q: "O mmc de 12 e 15 é:", options: ["30", "45", "60", "90"], correct: 2, subject: "Matemática" },
    { q: "Base 10 e altura 8. Base dobra e altura cai pela metade. Área:", options: ["Dobra", "Cai metade", "Fica igual", "Aumenta 50%"], correct: 2, subject: "Matemática" },
    { q: "Quantos anagramas possui a palavra 'CENSO'?", options: ["24", "60", "120", "240"], correct: 2, subject: "Matemática" },
    { q: "Ontem foi terça-feira. Que dia será daqui a 50 dias?", options: ["Quarta", "Quinta", "Sexta", "Sábado"], correct: 0, subject: "Matemática" },
    { q: "Mapa 1:50.000. Distância de 4cm equivale a:", options: ["1 km", "2 km", "4 km", "5 km"], correct: 1, subject: "Matemática" },
    { q: "Volume de reservatório 2m x 3m x 1,5m:", options: ["6m³", "9m³", "7,5m³", "10m³"], correct: 1, subject: "Matemática" },
    { q: "Capital R$ 1000 rendeu R$ 100 em 5 meses (simples). Taxa mensal:", options: ["1%", "2%", "5%", "10%"], correct: 1, subject: "Matemática" },
    { q: "Resolva: (2 + 3) * 4 - 10 / 2", options: ["10", "15", "25", "17"], correct: 1, subject: "Matemática" },
    { q: "Quantos números primos entre 1 e 20?", options: ["7", "8", "9", "10"], correct: 1, subject: "Matemática" },
    { q: "Se x + y = 10 e x - y = 4, x² - y² é:", options: ["14", "40", "100", "16"], correct: 1, subject: "Matemática" },
    { q: "Ângulo de 3/4 de volta completa mede:", options: ["90°", "180°", "270°", "300°"], correct: 2, subject: "Matemática" },
    { q: "Se 2^x = 32, então x² é:", options: ["5", "10", "25", "50"], correct: 2, subject: "Matemática" },
    { q: "Fração 3/8 em porcentagem:", options: ["30%", "37,5%", "38%", "40%"], correct: 1, subject: "Matemática" },
    { q: "Mdc de 24 e 36:", options: ["6", "12", "18", "24"], correct: 1, subject: "Matemática" },
    { q: "Ângulo dos ponteiros às 3 horas:", options: ["45°", "90°", "120°", "180°"], correct: 1, subject: "Matemática" },
    { q: "Soma de dois é 50 e um é o triplo do outro. Menor:", options: ["10", "12,5", "15", "20"], correct: 1, subject: "Matemática" },
    { q: "Negação de 'P e Q':", options: ["Não P e Não Q", "Não P ou Não Q", "Se P então Q", "P ou Q"], correct: 1, subject: "Matemática" },
    { q: "Polígono de 8 lados:", options: ["Heptágono", "Octógono", "Eneágono", "Decágono"], correct: 1, subject: "Matemática" },
    { q: "Se log10(x) = 3, então x é:", options: ["30", "100", "1000", "300"], correct: 2, subject: "Matemática" },
    { q: "Segundos em 2h e 15min:", options: ["7200s", "8100s", "9000s", "7500s"], correct: 1, subject: "Matemática" }
];
