const questionsMat = [
    { q: "Felipe gastou R$90 com meias de R$12 e R$15. Qual o máximo de pares de R$12 que ele comprou?", options: ["6", "5", "4", "3"], correct: 1, subject: "Matemática" },
    { q: "Sérgio deve R$7,50. Usando moedas de 0,25, 0,50 ou 1,00, qual a diferença entre a maior e menor quantidade de moedas?", options: ["20", "22", "15", "12"], correct: 1, subject: "Matemática" },
    { q: "Uma equipe tem 60 membros, sendo 6 mulheres a mais que homens. A razão mulheres/homens é:", options: ["11/9", "9/11", "33/27", "5/6"], correct: 0, subject: "Matemática" },
    { q: "Sete amigos dividem a conta. Um esqueceu a carteira e cada um pagou +R$14,50. O total foi:", options: ["R$522", "R$609", "R$588", "R$630"], correct: 1, subject: "Matemática" },
    { q: "Se Roberto é vascaíno, Jair é botafoguense. Se Jair não é botafoguense, conclui-se:", options: ["Sérgio é tricolor", "Roberto não é vascaíno", "Roberto é vascaíno", "Jair é vascaíno"], correct: 1, subject: "Matemática" },
    { q: "Cada chiclete custa R$1. Pacote com 5 custa R$4 e com 10 custa R$7. Com R$90, Bia compra no máximo:", options: ["103", "115", "127", "128"], correct: 2, subject: "Matemática" },
    { q: "Lucas gasta 1h20min no trânsito. Sem trânsito (20km/h a mais) gasta 48min. A distância é:", options: ["36km", "40km", "48km", "60km"], correct: 1, subject: "Matemática" },
    { q: "Juliana lê livros em 2, 3, 4 dias... sucessivamente. Terminou o 1º domingo e o 2º quarta. O 10º termina:", options: ["Sábado", "Domingo", "Segunda", "Quarta"], correct: 1, subject: "Matemática" },
    { q: "Leo atendeu 24 pacientes/dia por 3 dias e 32 pacientes/dia por 2 dias. O total foi:", options: ["56", "136", "124", "140"], correct: 1, subject: "Matemática" },
    { q: "Arquimedes corria 15km em 1h45min. Agora caminha 8km em 1h20min. Para 1km ele gasta a mais:", options: ["2 min", "3 min", "5 min", "10 min"], correct: 1, subject: "Matemática" },
    { q: "Se 3 recenseadores visitam 120 casas em 4 dias, quantos dias 2 levarão para 100 casas?", options: ["5 dias", "6 dias", "4 dias", "8 dias"], correct: 1, subject: "Matemática" },
    { q: "A negação de 'Todo recenseador usa colete' é:", options: ["Nenhum usa colete.", "Algum não usa colete.", "Todos usam colete.", "Algum usa colete."], correct: 1, subject: "Matemática" },
    { q: "Um aluguel de 25% da renda subiu 10%. Quanto da renda ocupará agora?", options: ["35%", "27,5%", "26%", "30%"], correct: 1, subject: "Matemática" },
    { q: "Se 'P então Q' é falso, então:", options: ["P e Q falsos.", "P verdade e Q falso.", "P falso e Q verdade.", "P e Q verdades."], correct: 1, subject: "Matemática" },
    { q: "Produto de R$ 80 teve aumento de 20% e desconto de 20%. Preço final:", options: ["R$ 80,00", "R$ 76,80", "R$ 64,00", "R$ 82,40"], correct: 1, subject: "Matemática" },
    { q: "60 homens e 40 mulheres. 20% dos homens e 10% das mulheres não responderam. Total:", options: ["12", "16", "20", "25"], correct: 1, subject: "Matemática" },
    { q: "Próximo número da sequência: 2, 3, 5, 8, 12...?", options: ["15", "17", "18", "20"], correct: 1, subject: "Matemática" },
    { q: "Média de 3 pessoas é 20 anos. Entra uma de 40 anos. Nova média:", options: ["22 anos", "25 anos", "28 anos", "30 anos"], correct: 1, subject: "Matemática" },
    { q: "5 bolas azuis e 3 vermelhas. Sorteando duas sem reposição, ambas azuis:", options: ["25/64", "5/14", "10/28", "20/56"], correct: 1, subject: "Matemática" },
    { q: "4 canetas e 3 lápis = R$ 15. 2 canetas e 1 lápis = R$ 7. Caneta custa:", options: ["R$ 2,00", "R$ 3,00", "R$ 4,00", "R$ 2,50"], correct: 1, subject: "Matemática" },
    { q: "O mmc de 12 e 15 é:", options: ["30", "45", "60", "90"], correct: 2, subject: "Matemática" },
    { q: "Base 10 e altura 8. Base dobra e altura cai pela metade. Área:", options: ["Dobra", "Cai metade", "Fica igual", "Aumenta 50%"], correct: 2, subject: "Matemática" },
    { q: "Quantos anagramas possui a palavra 'CENSO'?", options: ["24", "60", "120", "240"], correct: 2, subject: "Matemática" },
    { q: "Ontem foi terça-feira. Que dia será daqui a 50 dias?", options: ["Quarta", "Quinta", "Sexta", "Sábado"], correct: 0, subject: "Matemática" },
    { q: "Mapa 1:50.000. Distância de 4cm equivale a:", options: ["1 km", "2 km", "4 km", "5 km"], correct: 1, subject: "Matemática" },
    { q: "Volume de reservatório 2m x 3m x 1,5m:", options: ["6m³", "9m³", "7,5m³", "10m³"], correct: 1, subject: "Matemática" },
    { q: "Capital R$ 1000 rendeu R$ 100 em 5 meses (simples). Taxa mensal:", options: ["1%", "2%", "5%", "10%"], correct: 1, subject: "Matemática" },
    { q: "Resolva: (2 + 3) * 4 - 10 / 2", options: ["10", "15", "25", "17"], correct: 1, subject: "Matemática" },
    { q: "Quantos números primos entre 1 e 20?", options: ["7", "8", "9", "10"], correct: 1, subject: "Matemática" },
    { q: "Se x + y = 10 e x - y = 4, x² - y² é:", options: ["14", "40", "100", "16"], correct: 1, subject: "Matemática" },
    { q: "Ângulo de 3/4 de volta completa mede:", options: ["90°", "180°", "270°", "300°"], correct: 2, subject: "Matemática" },
    { q: "Se 2^x = 32, então x² é:", options: ["5", "10", "25", "50"], correct: 2, subject: "Matemática" },
    { q: "Fração 3/8 em porcentagem:", options: ["30%", "37,5%", "38%", "40%"], correct: 1, subject: "Matemática" },
    { q: "Mdc de 24 e 36:", options: ["6", "12", "18", "24"], correct: 1, subject: "Matemática" },
    { q: "Ângulo dos ponteiros às 3 horas:", options: ["45°", "90°", "120°", "180°"], correct: 1, subject: "Matemática" },
    { q: "Soma de dois é 50 e um é o triplo do outro. Menor:", options: ["10", "12,5", "15", "20"], correct: 1, subject: "Matemática" },
    { q: "Negação de 'P e Q':", options: ["Não P e Não Q", "Não P ou Não Q", "Se P então Q", "P ou Q"], correct: 1, subject: "Matemática" },
    { q: "Polígono de 8 lados:", options: ["Heptágono", "Octógono", "Eneágono", "Decágono"], correct: 1, subject: "Matemática" },
    { q: "Se log10(x) = 3, então x é:", options: ["30", "100", "1000", "300"], correct: 2, subject: "Matemática" },
    { q: "Segundos em 2h e 15min:", options: ["7200s", "8100s", "9000s", "7500s"], correct: 1, subject: "Matemática" }
];
