const questionsMat = [
    { q: "Quanto é 15% de 200?", options: ["20", "25", "30", "35"], correct: 2, subject: "Matemática" },
    { q: "Se 2x = 10, quanto é x?", options: ["2", "5", "8", "10"], correct: 1, subject: "Matemática" },
    { q: "Média de 10, 20 e 30:", options: ["10", "15", "20", "25"], correct: 2, subject: "Matemática" },
    { q: "Quantos minutos tem 2 horas e meia?", options: ["120", "150", "180", "200"], correct: 1, subject: "Matemática" },
    { q: "Raiz quadrada de 64:", options: ["6", "7", "8", "9"], correct: 2, subject: "Matemática" },
    { q: "Qual o próximo número: 2, 4, 8, 16...", options: ["20", "24", "30", "32"], correct: 3, subject: "Matemática" },
    { q: "Um terreno de 10m x 20m tem área de:", options: ["30m²", "100m²", "200m²", "2000m²"], correct: 2, subject: "Matemática" },
    { q: "Se 3 canetas custam 9 reais, quanto custam 10?", options: ["20", "27", "30", "33"], correct: 2, subject: "Matemática" },
    { q: "50% de 50 é:", options: ["5", "10", "25", "50"], correct: 2, subject: "Matemática" },
    { q: "O dobro de 15 somado com 10:", options: ["25", "40", "50", "60"], correct: 1, subject: "Matemática" },
    { q: "Quantos segundos tem 1 minuto?", options: ["10", "30", "60", "100"], correct: 2, subject: "Matemática" },
    { q: "O que é um triângulo isósceles?", options: ["3 lados iguais", "2 lados iguais", "Lados diferentes", "Sem lados"], correct: 1, subject: "Matemática" },
    { q: "Qual o valor de 2 elevado a 3?", options: ["5", "6", "8", "9"], correct: 2, subject: "Matemática" },
    { q: "1000 gramas equivalem a:", options: ["1kg", "10kg", "100kg", "0,1kg"], correct: 0, subject: "Matemática" },
    { q: "Se ontem foi terça, depois de amanhã será:", options: ["Quinta", "Sexta", "Sábado", "Domingo"], correct: 1, subject: "Matemática" },
    { q: "Resultado de (10 + 5) * 2:", options: ["20", "25", "30", "35"], correct: 2, subject: "Matemática" },
    { q: "O número 13 é:", options: ["Par", "Primo", "Divisível por 3", "Composto"], correct: 1, subject: "Matemática" },
    { q: "Qual a metade de 0,5?", options: ["0,1", "0,2", "0,25", "1"], correct: 2, subject: "Matemática" },
    { q: "Soma dos ângulos internos de um triângulo:", options: ["90°", "180°", "360°", "45°"], correct: 1, subject: "Matemática" },
    { q: "Quantos centímetros tem 1 metro?", options: ["10", "100", "1000", "1"], correct: 1, subject: "Matemática" }
{ q: "Se uma pizza custa R$ 40,00 e tem 10% de desconto, qual o preço final?", options: ["30", "34", "36", "38"], correct: 2, subject: "Matemática" },
    { q: "Qual o valor de 5! (fatorial de 5)?", options: ["25", "60", "100", "120"], correct: 3, subject: "Matemática" },
    { q: "Um trem percorre 120km em 2 horas. Qual sua velocidade média?", options: ["50km/h", "60km/h", "70km/h", "80km/h"], correct: 1, subject: "Matemática" },
    { q: "Quantos graus tem um ângulo reto?", options: ["45°", "90°", "180°", "360°"], correct: 1, subject: "Matemática" },
    { q: "Se x + 7 = 15, qual o valor de x?", options: ["7", "8", "9", "10"], correct: 1, subject: "Matemática" },
    { q: "Qual o próximo número primo após o 7?", options: ["8", "9", "10", "11"], correct: 3, subject: "Matemática" },
    { q: "Um ângulo de 180 graus é chamado de:", options: ["Agudo", "Obtuso", "Raso", "Reto"], correct: 2, subject: "Matemática" },
    { q: "Quantos lados tem um heptágono?", options: ["5", "6", "7", "8"], correct: 2, subject: "Matemática" },
    { q: "Qual a terça parte de 90?", options: ["20", "30", "45", "60"], correct: 1, subject: "Matemática" },
    { q: "Se eu comprar 3 doces por R$ 1,50 cada, quanto gasto?", options: ["3,00", "4,00", "4,50", "5,00"], correct: 2, subject: "Matemática" }
];