const questionsPort = [
    { q: "Qual a função sintática de 'o aluno' em: 'O aluno estudou'?", options: ["Objeto", "Sujeito", "Predicado", "Adjunto"], correct: 1, subject: "Português" },
    { q: "Assinale a opção com erro de acentuação:", options: ["Café", "Saúde", "Ítem", "Lâmpada"], correct: 2, subject: "Português" },
    { q: "Escolha a forma correta:", options: ["A gente fomos", "Nós foi", "Eles vieram", "Eu fizem"], correct: 2, subject: "Português" },
    { q: "Sinônimo de 'Perspicaz':", options: ["Lento", "Esperto", "Triste", "Comum"], correct: 1, subject: "Português" },
    { q: "Antônimo de 'Altruísmo':", options: ["Bondade", "Caridade", "Egoísmo", "Zelo"], correct: 2, subject: "Português" },
    { q: "Qual frase está na voz passiva?", options: ["O bolo foi comido", "Ele comeu o bolo", "Comi o bolo", "Comeremos o bolo"], correct: 0, subject: "Português" },
    { q: "Assinale a frase com uso correto da crase:", options: ["Fui à feira", "Fui a pé", "Diga à ele", "De dia à dia"], correct: 0, subject: "Português" },
    { q: "Plural de 'Cidadão':", options: ["Cidadões", "Cidadães", "Cidadãos", "Cidadão"], correct: 2, subject: "Português" },
    { q: "Significado de 'Ambíguo':", options: ["Claro", "Dois sentidos", "Rápido", "Antigo"], correct: 1, subject: "Português" },
    { q: "Figura de linguagem em 'O sol sorriu':", options: ["Metáfora", "Personificação", "Hipérbole", "Ironia"], correct: 1, subject: "Português" },
    { q: "Coletivo de 'Lobos':", options: ["Cardume", "Alcateia", "Enxame", "Rebanho"], correct: 1, subject: "Português" },
    { q: "Classe gramatical de 'Lentamente':", options: ["Substantivo", "Adjetivo", "Advérbio", "Verbo"], correct: 2, subject: "Português" },
    { q: "Dígrafo na palavra:", options: ["Prato", "Carro", "Bloco", "Treino"], correct: 1, subject: "Português" },
    { q: "Conjunção adversativa:", options: ["E", "Mas", "Ou", "Porque"], correct: 1, subject: "Português" },
    { q: "Pronome de tratamento para Reitores:", options: ["V. Excelência", "V. Magnificência", "V. Senhoria", "V. Alteza"], correct: 1, subject: "Português" },
    { q: "Qual é o ditongo?", options: ["Pai", "Saúde", "Baú", "Lago"], correct: 0, subject: "Português" },
    { q: "Verbo no pretérito perfeito:", options: ["Estudei", "Estudo", "Estudarei", "Estudaria"], correct: 0, subject: "Português" },
    { q: "Indique o adjetivo:", options: ["Correr", "Feliz", "Mesa", "Ontem"], correct: 1, subject: "Português" },
    { q: "Uso do 'onde':", options: ["Onde você mora?", "Onde você fez isso?", "Aonde você quer chegar?", "Onde você pensou?"], correct: 0, subject: "Português" },
    { q: "Oxítona terminada em 'a':", options: ["Mesa", "Pará", "Livro", "Porta"], correct: 1, subject: "Português" },
    { q: "Qual a forma correta de grafia?", options: ["Excessão", "Exceção", "Eçessão", "Exsessão"], correct: 1, subject: "Português" },
    { q: "O antônimo de 'Efêmero' é:", options: ["Breve", "Passageiro", "Duradouro", "Curto"], correct: 2, subject: "Português" },
    { q: "Em 'Falar é prata, calar é ouro', temos:", options: ["Metáfora", "Antítese", "Hipérbole", "Eufemismo"], correct: 1, subject: "Português" },
    { q: "Erro de concordância em:", options: ["Seguem anexos", "É meio-dia e meia", "A entrada é proibido", "Havia pessoas"], correct: 2, subject: "Português" },
    { q: "Sujeito de: 'Venderam-se as casas':", options: ["Indeterminado", "As casas", "Eles", "Oculto"], correct: 1, subject: "Português" },
    { q: "Substantivo abstrato:", options: ["Cadeira", "Beleza", "Caneta", "Computador"], correct: 1, subject: "Português" },
    { q: "Pronome demonstrativo:", options: ["Eu", "Aquele", "Meu", "Quem"], correct: 1, subject: "Português" },
    { q: "Aumentativo de 'Corpo':", options: ["Corpão", "Corpanzil", "Corpúsculo", "Corpaço"], correct: 1, subject: "Português" },
    { q: "Significado de 'Ratificar':", options: ["Corrigir", "Confirmar", "Mudar", "Esquecer"], correct: 1, subject: "Português" },
    { q: "Erro de ortografia em:", options: ["Analisar", "Paralizar", "Pesquisar", "Avisar"], correct: 1, subject: "Português" }
];