const questionsPort = [
    { q: "A frase 'O IBGE é o provedor das informações; todavia, a precisão depende do informante' mantém o sentido original se substituirmos o conectivo por:", options: ["Porquanto", "Contudo", "Conquanto", "Portanto"], correct: 1, subject: "Português" },
    { q: "Assinale a opção em que a inversão dos termos altera o sentido original: 'Grande homem' / 'Homem grande'.", options: ["Pobre criança / Criança pobre", "Belo dia / Dia belo", "Forte vento / Vento forte", "Antigo colega / Colega antigo"], correct: 0, subject: "Português" },
    { q: "Na frase 'É necessário que se diga a verdade', a oração sublinhada classifica-se como:", options: ["Objetiva Direta", "Subjetiva", "Completiva Nominal", "Apositiva"], correct: 1, subject: "Português" },
    { q: "Em 'O recenseador visitou a vila cujas casas eram azuis', o pronome 'cujas' indica:", options: ["Lugar", "Causa", "Posse", "Modo"], correct: 2, subject: "Português" },
    { q: "Assinale a alternativa que apresenta a regência verbal correta de acordo com a norma culta:", options: ["O candidato visava ao cargo.", "Ele assistiu o filme ontem.", "Prefiro café do que chá.", "Esqueci do meu documento."], correct: 0, subject: "Português" },
    { q: "A palavra 'estatística' recebe acento pelo mesmo motivo que:", options: ["Pará", "Saúde", "Público", "Ítem"], correct: 2, subject: "Português" },
    { q: "Assinale a frase em que o uso da vírgula está INCORRETO:", options: ["Ontem, os técnicos chegaram.", "O Censo, que é importante, começou.", "Os alunos, estudaram muito para a prova.", "João, traga os formulários."], correct: 2, subject: "Português" },
    { q: "O antônimo de 'Meticuloso' é:", options: ["Cuidadoso", "Negligente", "Diligente", "Perfeccionista"], correct: 1, subject: "Português" },
    { q: "Qual o sentido do prefixo na palavra 'Analfabeto'?", options: ["Repetição", "Negação", "Proximidade", "Movimento para fora"], correct: 1, subject: "Português" },
    { q: "Em 'Falaram de você na reunião', o sujeito é classificado como:", options: ["Simples", "Oculto", "Indeterminado", "Inexistente"], correct: 2, subject: "Português" },
    { q: "Indique a opção com erro de ortografia:", options: ["Exceção", "Pretensioso", "Ascensão", "Chuchu"], correct: 1, subject: "Português" },
    { q: "A locução 'à medida que' exprime ideia de:", options: ["Causa", "Consequência", "Proporção", "Tempo"], correct: 2, subject: "Português" },
    { q: "O plural de 'Cidadão' e 'Escrivão' é:", options: ["Cidadões e Escrivões", "Cidadãos e Escrivães", "Cidadãos e Escrivãos", "Cidadães e Escrivães"], correct: 1, subject: "Português" },
    { q: "Assinale a frase com uso correto da crase:", options: ["Refiro-me à pessoas honestas.", "Fui àquela cidade.", "Diga à ele a verdade.", "Andamos à pé."], correct: 1, subject: "Português" },
    { q: "O verbo 'haver' em 'Havia muitas pessoas no posto' é:", options: ["Transitivo Indireto", "Impessoal", "Auxiliar", "De ligação"], correct: 1, subject: "Português" },
    { q: "Significado de 'Efêmero':", options: ["Duradouro", "Passageiro", "Rápido", "Importante"], correct: 1, subject: "Português" },
    { q: "A concordância está correta em:", options: ["Faziam muitos dias que não chovia.", "Houveram muitos acertos.", "Seguem anexas as fotos.", "É proibido a entrada."], correct: 2, subject: "Português" },
    { q: "A palavra 'incipiente' significa:", options: ["Sábio", "Principiante", "Ignorante", "Atrasado"], correct: 1, subject: "Português" },
    { q: "Em 'O sol brilhava; os pássaros cantavam', o ponto e vírgula separa orações:", options: ["Coordenadas", "Subordinadas", "Intercaladas", "Expletivas"], correct: 0, subject: "Português" },
    { q: "O termo 'Retificar' significa:", options: ["Confirmar", "Corrigir", "Anular", "Adiar"], correct: 1, subject: "Português" },
    { q: "Adjetivo pátrio de quem nasce no Espírito Santo:", options: ["Espirituense", "Capixaba", "Santista", "Sulsantense"], correct: 1, subject: "Português" },
    { q: "O coletivo de 'Embaixadores' é:", options: ["Súcia", "Comitiva", "Cortejo", "Séquito"], correct: 3, subject: "Português" },
    { q: "Na frase 'Ele é muito inteligente', o termo 'muito' é:", options: ["Adjetivo", "Pronome", "Advérbio de intensidade", "Substantivo"], correct: 2, subject: "Português" },
    { q: "Qual o superlativo de 'Humilde'?", options: ["Humildíssimo", "Humílimo", "Muito humilde", "Humildezão"], correct: 1, subject: "Português" },
    { q: "Indique a alternativa sem erro de grafia:", options: ["Analisar, puzeram", "Analisar, puseram", "Analizar, puseram", "Analizar, puzeram"], correct: 1, subject: "Português" },
    { q: "A conjunção 'conquanto' tem valor de:", options: ["Causa", "Conclusão", "Concessão", "Adição"], correct: 2, subject: "Português" },
    { q: "Em 'Trabalho para o IBGE', o termo 'para o IBGE' indica:", options: ["Causa", "Finalidade", "Conformidade", "Tempo"], correct: 1, subject: "Português" },
    { q: "O plural de 'Pôr do sol' é:", options: ["Pores do sol", "Pôr do sóis", "Pores dos sóis", "Pôr dos sol"], correct: 0, subject: "Português" },
    { q: "Significado de 'Altruísta':", options: ["Egoísta", "Desprendido", "Orgulhoso", "Rico"], correct: 1, subject: "Português" },
    { q: "A voz passiva de 'O recenseador fez a entrevista' é:", options: ["A entrevista foi feita pelo recenseador.", "Fez-se a entrevista.", "A entrevista se fez.", "A entrevista faria o recenseador."], correct: 0, subject: "Português" }
];
