const questionsPort = [
    // --- Questões da Prova Enviada ---
    { q: "A primeira frase do texto diz que a democracia 'reclama um jornalismo vigoroso'. Isso significa que a democracia:", options: ["Não está satisfeita com o atual", "Prefere um jornalismo menos agressivo", "Exige dos jornais força e independência", "Protesta contra um jornalismo fraco"], correct: 2, subject: "Português" },
    { q: "A substituição de adjetivo por locução está adequada em:", options: ["Independente = com dependência", "Pública = de publicidade", "Relevante = de relevância", "Sociais = de associados"], correct: 2, subject: "Português" },
    { q: "O conectivo 'Mas' em 'Mas o pontapé inicial...' pode ser substituído por:", options: ["Logo", "Pois", "Portanto", "Contudo"], correct: 3, subject: "Português" },
    { q: "As orações 'Atentados matam 44' e 'país decreta emergência' mantêm relação de:", options: ["Causa e consequência", "Informação e comprovação", "Fato e exemplificação", "Tese e argumentação"], correct: 0, subject: "Português" },
    { q: "Sobre concordância nominal em 'empresas de conteúdo independentes', o adjetivo está no plural porque:", options: ["Refere-se a empresas", "Refere-se a conteúdo", "Concorda com o presidente", "É uma exceção gramatical"], correct: 0, subject: "Português" },
    { q: "A oração reduzida 'para evitar a abstenção' equivale a:", options: ["Para que se evite a abstenção", "A fim de que a abstenção fosse evitada", "Evitando-se a abstenção", "Para que se evitasse a abstenção"], correct: 0, subject: "Português" },
    { q: "Dizer que a Guerra é uma 'página desbotada na memória' significa que ela:", options: ["Deve ser esquecida", "Traz remorsos", "É pouco conhecida e discutida no presente", "Foi modificada por ideologias"], correct: 2, subject: "Português" },
    { q: "A troca de posição provoca modificação de sentido em:", options: ["Página desbotada", "Conflito sangrento", "Discussões acadêmicas", "Grande reportagem"], correct: 3, subject: "Português" },
    { q: "Qual a função do texto na contracapa de um livro?", options: ["Criticar o autor", "Promover a venda indicando qualidades", "Resumir o final da história", "Listar erros históricos"], correct: 1, subject: "Português" },
    { q: "Na passagem 'Rio receberá mais vacinas... Os estoques tinham se esgotado', o 2º período indica:", options: ["Consequência", "Causa", "Explicação", "Exemplificação"], correct: 1, subject: "Português" },
    // --- Questões Extras (Estilo FGV) ---
    { q: "Assinale a frase em que o termo 'onde' está usado corretamente:", options: ["Vivemos uma época onde todos opinam", "A reunião onde decidimos as metas", "A cidade onde nasci é calma", "O argumento onde ele se baseou"], correct: 2, subject: "Português" },
    { q: "Em 'A economia costuma contorcer as palavras', a figura de linguagem presente é:", options: ["Metáfora", "Personificação", "Hipérbole", "Eufemismo"], correct: 1, subject: "Português" },
    { q: "O antônimo de 'Moderada' no contexto 'intensificação moderada' seria:", options: ["Suave", "Equilibrada", "Drástica", "Lenta"], correct: 2, subject: "Português" },
    { q: "A palavra 'emergência' recebe acento pelo mesmo motivo de:", options: ["Públicas", "Indígenas", "História", "Século"], correct: 2, subject: "Português" },
    { q: "No trecho 'que, ocultas no sertão, foram mais preservadas', o termo entre vírgulas indica:", options: ["Tempo", "Causa", "Lugar", "Finalidade"], correct: 1, subject: "Português" },
    { q: "Assinale a frase com erro de regência verbal:", options: ["Assisti ao filme ontem", "Cheguei no Rio de Janeiro", "Obedeço aos meus pais", "Aspiro ao cargo de técnico"], correct: 1, subject: "Português" },
    { q: "Qual o sentido da expressão 'coroamento do trabalho'?", options: ["O início", "O fracasso", "A finalização com êxito", "A interrupção"], correct: 2, subject: "Português" },
    { q: "Em 'a maior parte habitantes de reservas', a concordância poderia ser:", options: ["Sempre no singular", "Sempre no plural", "Facultativa (Singular ou Plural)", "Apenas com o numeral"], correct: 2, subject: "Português" },
    { q: "A intenção principal de uma manchete de jornal é:", options: ["Confundir o leitor", "Relatar detalhes minuciosos", "Informar o fato principal de forma rápida", "Expressar a opinião do dono do jornal"], correct: 2, subject: "Português" },
    { q: "Substituir 'embora' por um conectivo de mesmo valor:", options: ["Todavia", "Apesar de que", "Portanto", "Visto que"], correct: 1, subject: "Português" },
    { q: "A palavra 'vultosa' em 'economia vultosa' significa:", options: ["Pequena", "Grande/Volumosa", "Perigosa", "Inexistente"], correct: 1, subject: "Português" },
    { q: "O sinal de crase é proibido em:", options: ["Às duas horas", "À medida que", "A partir de agora", "À disposição"], correct: 2, subject: "Português" },
    { q: "Na frase 'Disse que a redução terá...', o termo 'que' inicia uma oração:", options: ["Adjetiva", "Substantiva Objetiva Direta", "Adverbial Temporal", "Conclusiva"], correct: 1, subject: "Português" },
    { q: "Dizer 'restaram pouco mais de 200 mil' implica que:", options: ["Exatamente 200 mil sobraram", "Menos de 200 mil sobraram", "Um número ligeiramente superior a 200 mil sobrou", "Ninguém sobrou"], correct: 2, subject: "Português" },
    { q: "O plural de 'Cidadão' e 'Escrivão' é:", options: ["Cidadões e Escrivães", "Cidadãos e Escrivãos", "Cidadãos e Escrivães", "Cidadões e Escrivãos"], correct: 2, subject: "Português" },
    { q: "A expressão 'Palco dos acontecimentos' é uma:", options: ["Ironia", "Metonímia", "Metáfora", "Pleonasmo"], correct: 2, subject: "Português" },
    { q: "O sufixo '-mente' em 'integralmente' indica:", options: ["Tempo", "Modo", "Lugar", "Dúvida"], correct: 1, subject: "Português" },
    { q: "A FGV considera 'atendimento polido' como:", options: ["Falar difícil", "Ser educado e cordial", "Ignorar o cliente", "Informar apenas o básico"], correct: 1, subject: "Português" },
    { q: "A pontuação está correta em:", options: ["João, comprou o livro.", "Ontem à noite, fomos ao cinema.", "O Brasil, é um país grande.", "Espero que, você passe."], correct: 1, subject: "Português" },
    { q: "Qual termo é sinônimo de 'Remanescentes'?", options: ["Novos", "Sobreviventes/Restantes", "Antigos", "Líderes"], correct: 1, subject: "Português" },
    { q: "A frase 'A democracia reclama um jornalismo vigoroso' significa que a democracia:", options: ["Não aceita o jornalismo atual", "Exige força e independência", "Protesta contra a imprensa", "Prefere jornais agressivos"], correct: 1, subject: "Português" },
    { q: "Na frase 'Mas o pontapé inicial é das empresas', a conjunção 'Mas' pode ser substituída por:", options: ["Portanto", "Logo", "Contudo", "Pois"], correct: 2, subject: "Português" },
    { q: "Assinale a substituição adequada para o adjetivo sublinhado: 'Relevante' =", options: ["De relevância", "Com pressa", "De publicidade", "Sem importância"], correct: 0, subject: "Português" },
    { q: "Em 'Atentados matam 44 e país decreta emergência', as orações indicam relação de:", options: ["Afirmação e explicação", "Fato e exemplificação", "Causa e consequência", "Tese e argumento"], correct: 2, subject: "Português" },
    { q: "Dizer que um fato é uma 'página desbotada na memória' significa que ele é:", options: ["Muito importante", "Inesquecível", "Pouco conhecido no presente", "Modificado por ideologias"], correct: 2, subject: "Português" },
    { q: "Assinale a concordância CORRETA:", options: ["Os adjetivos referem-se a dois substantivos", "A forma 'determinada' refere-se a 'imprensa'", "O adjetivo 'independentes' refere-se a 'conteúdo'", "A democracia reclamam o jornalismo"], correct: 1, subject: "Português" },
    { q: "A oração reduzida 'para evitar a abstenção' desenvolvida corretamente é:", options: ["Para que se evite a abstenção", "Evitando-se a abstenção", "A fim de evitar-se", "Para que se evitasse"], correct: 0, subject: "Português" },
    { q: "Indique o par onde a troca de posição altera o sentido (estilo 'Homem grande' / 'Grande homem'):", options: ["Página desbotada", "Pesquisas rigorosas", "Grande reportagem", "Conflito sangrento"], correct: 2, subject: "Português" },
    { q: "No termo 'Século XXI', o numeral romano deve ser lido como:", options: ["Cardinal (Vinte e um)", "Ordinal (Vigésimo primeiro)", "Fracionário", "Multiplicativo"], correct: 1, subject: "Português" },
    { q: "A frase 'O Rio receberá vacinas. Os estoques tinham se esgotado' indica relação de:", options: ["Consequência", "Causa", "Explicação", "Resumo"], correct: 1, subject: "Português" },
    { q: "A frase 'O IBGE é o provedor das informações; todavia, a precisão depende do informante' mantém o sentido original se substituirmos o conectivo por:", options: ["Porquanto", "Contudo", "Conquanto", "Portanto"], correct: 1, subject: "Português" },
    { q: "Assinale a opção em que a inversão dos termos altera o sentido original: 'Grande homem' / 'Homem grande'.", options: ["Pobre criança / Criança pobre", "Belo dia / Dia belo", "Forte vento / Vento forte", "Antigo colega / Colega antigo"], correct: 0, subject: "Português" },
    { q: "Na frase 'É necessário que se diga a verdade', a oração sublinhada classifica-se como:", options: ["Objetiva Direta", "Subjetiva", "Completiva Nominal", "Apositiva"], correct: 1, subject: "Português" },
    { q: "Em 'O recenseador visitou a vila cujas casas eram azuis', o pronome 'cujas' indica:", options: ["Lugar", "Causa", "Posse", "Modo"], correct: 2, subject: "Português" },
    { q: "Assinale a alternativa que apresenta a regência verbal correta de acordo com a norma culta:", options: ["O candidato visava ao cargo.", "Ele assistiu o filme ontem.", "Prefiro café do que chá.", "Esqueci do meu documento."], correct: 0, subject: "Português" },
    { q: "A palavra 'estatística' recebe acento pelo mesmo motivo que:", options: ["Pará", "Saúde", "Público", "Ítem"], correct: 2, subject: "Português" },
    { q: "Assinale a frase em que o uso da vírgula está INCORRETO:", options: ["Ontem, os técnicos chegaram.", "O Censo, que é importante, começou.", "Os alunos, estudaram muito para a prova.", "João, traga os formulários."], correct: 2, subject: "Português" },
    { q: "O antônimo de 'Meticuloso' é:", options: ["Cuidadoso", "Negligente", "Diligente", "Perfeccionista"], correct: 1, subject: "Português" },
    { q: "Qual o sentido do prefixo na palavra 'Analfabeto'?", options: ["Repetição", "Negação", "Proximidade", "Movimento para fora"], correct: 1, subject: "Português" },
    { q: "Em 'Falaram de você na reunião', o sujeito é classificado como:", options: ["Simples", "Oculto", "Indeterminado", "Inexistente"], correct: 2, subject: "Português" },
    { q: "Indique a opção com erro de ortografia:", options: ["Exceção", "Pretensioso", "Ascensão", "Chuchu"], correct: 1, subject: "Português" },
    { q: "A locução 'à medida que' exprime ideia de:", options: ["Causa", "Consequência", "Proporção", "Tempo"], correct: 2, subject: "Português" },
    { q: "O plural de 'Cidadão' e 'Escrivão' é:", options: ["Cidadões e Escrivões", "Cidadãos e Escrivães", "Cidadãos e Escrivãos", "Cidadães e Escrivães"], correct: 1, subject: "Português" },
    { q: "Assinale a frase com uso correto da crase:", options: ["Refiro-me à pessoas honestas.", "Fui àquela cidade.", "Diga à ele a verdade.", "Andamos à pé."], correct: 1, subject: "Português" },
    { q: "O verbo 'haver' em 'Havia muitas pessoas no posto' é:", options: ["Transitivo Indireto", "Impessoal", "Auxiliar", "De ligação"], correct: 1, subject: "Português" },
    { q: "Significado de 'Efêmero':", options: ["Duradouro", "Passageiro", "Rápido", "Importante"], correct: 1, subject: "Português" },
    { q: "A concordância está correta em:", options: ["Faziam muitos dias que não chovia.", "Houveram muitos acertos.", "Seguem anexas as fotos.", "É proibido a entrada."], correct: 2, subject: "Português" },
    { q: "A palavra 'incipiente' significa:", options: ["Sábio", "Principiante", "Ignorante", "Atrasado"], correct: 1, subject: "Português" },
    { q: "Em 'O sol brilhava; os pássaros cantavam', o ponto e vírgula separa orações:", options: ["Coordenadas", "Subordinadas", "Intercaladas", "Expletivas"], correct: 0, subject: "Português" },
    { q: "O termo 'Retificar' significa:", options: ["Confirmar", "Corrigir", "Anular", "Adiar"], correct: 1, subject: "Português" },
    { q: "Adjetivo pátrio de quem nasce no Espírito Santo:", options: ["Espirituense", "Capixaba", "Santista", "Sulsantense"], correct: 1, subject: "Português" },
    { q: "O coletivo de 'Embaixadores' é:", options: ["Súcia", "Comitiva", "Cortejo", "Séquito"], correct: 3, subject: "Português" },
    { q: "Na frase 'Ele é muito inteligente', o termo 'muito' é:", options: ["Adjetivo", "Pronome", "Advérbio de intensidade", "Substantivo"], correct: 2, subject: "Português" },
    { q: "Qual o superlativo de 'Humilde'?", options: ["Humildíssimo", "Humílimo", "Muito humilde", "Humildezão"], correct: 1, subject: "Português" },
    { q: "Indique a alternativa sem erro de grafia:", options: ["Analisar, puzeram", "Analisar, puseram", "Analizar, puseram", "Analizar, puzeram"], correct: 1, subject: "Português" },
    { q: "A conjunção 'conquanto' tem valor de:", options: ["Causa", "Conclusão", "Concessão", "Adição"], correct: 2, subject: "Português" },
    { q: "Em 'Trabalho para o IBGE', o termo 'para o IBGE' indica:", options: ["Causa", "Finalidade", "Conformidade", "Tempo"], correct: 1, subject: "Português" },
    { q: "O plural de 'Pôr do sol' é:", options: ["Pores do sol", "Pôr do sóis", "Pores dos sóis", "Pôr dos sol"], correct: 0, subject: "Português" },
    { q: "Significado de 'Altruísta':", options: ["Egoísta", "Desprendido", "Orgulhoso", "Rico"], correct: 1, subject: "Português" },
    { q: "A voz passiva de 'O recenseador fez a entrevista' é:", options: ["A entrevista foi feita pelo recenseador.", "Fez-se a entrevista.", "A entrevista se fez.", "A entrevista faria o recenseador."], correct: 0, subject: "Português" }
];
